name: Build website

on:
  pull_request: ~

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.1.2
        with:
          php-version: 7.4

      - name: Checkout Website repo
        run: |
          git clone --branch master https://${{ secrets.BOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/async-aws/website output

      - name: Commit & push the new files
        run: |
          cd output
          echo "foobar" > Foo.txt

          git config --local user.email "github@async-aws.com"
          git config --local user.name "AsyncAWS Bot"

          echo "::group::git push"
          git add .
          git commit -m "Update website from commit async-aws/aws@${{ github.sha }}" -a
          git push
          echo "::endgroup::"
